version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.12.0-management
    hostname: rabbitmsgqueue
    container_name: rabbitmq3
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"

volumes:
  rabbitmq:
    driver: local