version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=admin
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8080
    volumes:
      - /esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    deploy:
      resources: 
        limits: 
          cpus: "0.4"
          memory: 6G
  kibana:
    image: kibana:8.8.0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
  tika:
    image: apache/tika
    ports:
      - "9998:9998"
    restart: always
    deploy:
      resources: 
        limits: 
          cpus: "0.4"
          memory: 6G
volumes:
  esdata:
    driver: local